# railway.toml - Railway service configuration
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.backend"

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment variables for Railway
[[deploy.environmentVariables]]
name = "PYTHONUNBUFFERED"
value = "1"

[[deploy.environmentVariables]]
name = "PYTHONDONTWRITEBYTECODE"
value = "1"

# Database connections (Railway will auto-inject these)
[[deploy.environmentVariables]]
name = "DATABASE_URL"
value = "${{Postgres.DATABASE_URL}}"

[[deploy.environmentVariables]]
name = "REDIS_URL"
value = "${{Redis.REDIS_URL}}"

# App configuration
[[deploy.environmentVariables]]
name = "APP_ENV"
value = "production"

[[deploy.environmentVariables]]
name = "LOG_LEVEL"
value = "INFO"

---

# requirements.txt - Python dependencies for Railway
fastapi[all]==0.104.1
uvicorn[standard]==0.24.0
websockets==12.0
python-multipart==0.0.6
sqlalchemy==2.0.23
psycopg2-binary==2.9.9
redis==5.0.1
pandas==2.1.4
numpy==1.24.4
scikit-learn==1.3.2
matplotlib==3.8.2
seaborn==0.13.0
plotly==5.17.0
aiofiles==23.2.1
python-jose[cryptography]==3.3.0
passlib[bcrypt]==1.7.4
prometheus-client==0.19.0
psutil==5.9.6

# Synthetic data generation libraries
sdv==1.12.1
ctgan==0.7.3
copulas==0.10.1

# Additional ML libraries
scipy==1.11.4
tensorflow==2.15.0
torch==2.1.2

# Utility libraries
pydantic==2.5.2
python-dotenv==1.0.0
email-validator==2.1.0

---

# .railwayignore - Files to ignore during Railway deployment
.git/
.gitignore
.env
.env.*
*.log
*.tmp
__pycache__/
*.pyc
*.pyo
*.pyd
.Python
*.so
.coverage
.pytest_cache/
.mypy_cache/
.venv/
venv/
ENV/
env/
.DS_Store
Thumbs.db
*.swp
*.swo
*~
.idea/
.vscode/
*.md
docs/
tests/
node_modules/
.next/
build/
dist/

---

# .env.example - Environment variables template
# Copy this to .env and fill in your values

# Database Configuration
DATABASE_URL=postgresql://username:password@localhost:5432/synthetic_data
REDIS_URL=redis://localhost:6379

# Application Settings
APP_ENV=development
LOG_LEVEL=INFO
SECRET_KEY=your-secret-key-here

# CORS Settings
CORS_ORIGINS=http://localhost:3000,https://yourdomain.com

# File Upload Settings
MAX_UPLOAD_SIZE=100MB
UPLOAD_PATH=/app/uploads

# Synthetic Data Settings
DEFAULT_MODEL=CTGAN
MAX_SAMPLES=10000
DEFAULT_PRIVACY_LEVEL=medium

# Railway Specific (automatically set by Railway)
PORT=8000
RAILWAY_ENVIRONMENT=production

---

# Procfile - Railway process definition (alternative to railway.toml)
web: python main.py
worker: python worker.py

---

# nixpacks.toml - Alternative build configuration for Railway
[phases.setup]
nixPkgs = ['python39', 'gcc', 'pkg-config', 'libpq']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['python -m compileall .']

[start]
cmd = 'python main.py'